
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

language: c

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y expect trousers libldap2-dev libtspi-dev
before_script:
    - sudo groupadd pkcs11
    - ./bootstrap.sh
script:
    - ./configure --enable-testcases --enable-debug && make
    - sudo make install
    - sudo ldconfig
    - sudo pkcsslotd
    - sudo pkcsconf -t
    - cd testcases
    - sudo PKCS11_SO_PIN=87654321 PKCS11_USER_PIN=01234567 PKCSLIB=/usr/local/lib/pkcs11/libopencryptoki.so ./ock_tests.sh -s 3

notifications:
  slack:
    secure: dcaiPQdCGfoMNc8Hr4Mjg31cB2kY4XAE/ed2VNNZVGrbEdHLHzUKa55bGvRpxLgREWG6zly2izDpTS0lskO0WD7XS1ybLNT5AZITgN2Sa+yG87qHSMgFQybz5sgZtOzd6KFUH+Ft3OBbvRMMS+bUsd6GIoqguHV5eRUYZoa+3Gc7g0Hvo/2C4s5mGL4DrWHou8WnGI1nplvLgsadCjZdJ8y/yoX6ua3h1KNDpv9Mbe2SFb6b/t244p58+JwvVXyP8PEqzRtjuYE9PXLYTqwz0pYJlBmcLDCUXNeI9vdJ/+523A7YuaMq2spIKd0hLMqmJ2+CiC/iLM0dX9Are7f/BTsSfkcAYhjF0tmlHRUFuqLwRvEDjyNifMaGsTNuRDMAhEc2F77gIyvLA03EHKBhdVGlPT3+dwzpze0nDUP+ThneSgZplG7kuvBZ+ZdN0kaDZxzyPAXhCLxIg8vhJ9cPeI07dfoyOeGIoYSThk+MpOBKZUVmVF7APAM/ytALZ1Oycvvh2ApOdxl0or1ezTEFFArMoMNQOaIK6DNElsdYDyQopjtLq8ZOXhtNcaqOpZ0B95/qj4iPnoyk9sG592PYu3wzoVbXXuEWa7XCp+jiky5AUMOkxF9dpAmXkzkGyD+jFjhZ35VvGqshK3RmlNL81VNmA9Tm8LbkvQ4Tl1mvS1s=
